#define SPLASH_IMAGE 1
#define LOGO_IMAGE 2
#define MOSYNC_IMAGE 3
#define CONNECT_BG 4
#define RELOAD_BG 5
#define BACKGROUND 6
#define INFO_ICON 7
#define BEEP_WAV 8
#define INFO_TEXT 9
#define CUSTOM_JS 10
